[[redirects]]
  from = "/login"
  to = "https://relaxed-northcutt-53ebbd.netlify.app/"
  status = 200

[[redirects]]
  from = "/products"
  to = "https://relaxed-northcutt-53ebbd.netlify.app/products"
  status = 200

[[redirects]]
  from = "/signup"
  to = "https://relaxed-northcutt-53ebbd.netlify.app/signup"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/signup""
    [headers.values]
    Access-Control-Allow-Origin = "*"