[[redirects]]
  from = "/login"
  to = "https://buyma.netlify.app/"
  status = 200

[[redirects]]
  from = "/products"
  to = "https://buyma.netlify.app/products/"
  status = 200

[[redirects]]
  from = "/product"
  to = "https://buyma.netlify.app/product/"
  status = 200

[[redirects]]
  from = "/signup"
  to = "https://buyma.netlify.app/signup"
  status = 200